import 'package:flutter/material.dart';

/// Shared icon list for habit and tag forms
class IconConstants {
  static final List<IconData> commonIcons = [
    // Basic & Common
    Icons.label,
    Icons.category,
    Icons.star,
    Icons.favorite,
    Icons.home,
    
    // Work & Education
    Icons.work,
    Icons.school,
    Icons.business,
    Icons.apartment,
    
    // Health & Fitness
    Icons.fitness_center,
    Icons.directions_walk,
    Icons.directions_run,
    Icons.bike_scooter,
    Icons.directions_bike,
    Icons.pool,
    Icons.self_improvement,
    Icons.airline_seat_flat,
    Icons.health_and_safety,
    Icons.spa,
    
    // Sports & Activities
    Icons.sports_soccer,
    Icons.surfing,
    Icons.skateboarding,
    Icons.snowboarding,
    Icons.sailing,
    Icons.kayaking,
    Icons.hiking,
    Icons.forest,
    Icons.terrain,
    Icons.rocket_launch,
    
    // Food & Dining
    Icons.local_dining,
    Icons.restaurant,
    Icons.local_cafe,
    Icons.local_bar,
    Icons.coffee,
    
    // Entertainment
    Icons.music_note,
    Icons.movie,
    Icons.games,
    Icons.book,
    Icons.library_books,
    Icons.library_music,
    Icons.theater_comedy,
    Icons.video_library,
    Icons.menu_book,
    Icons.auto_stories,
    Icons.newspaper,
    Icons.article,
    
    // Nature & Animals
    Icons.nature,
    Icons.pets,
    Icons.beach_access,
    
    // Daily Life
    Icons.bedtime,
    Icons.water_drop,
    Icons.shopping_cart,
    Icons.shopping_bag,
    Icons.shopping_basket,
    
    // Travel & Transportation
    Icons.directions_car,
    Icons.flight,
    Icons.flight_takeoff,
    Icons.flight_land,
    Icons.hotel,
    Icons.train,
    Icons.directions_bus,
    Icons.directions_subway,
    Icons.directions_boat,
    Icons.local_taxi,
    Icons.map,
    Icons.place,
    Icons.location_on,
    Icons.navigation,
    Icons.explore,
    Icons.travel_explore,
    
    // Finance
    Icons.account_balance,
    Icons.account_balance_wallet,
    Icons.savings,
    Icons.payments,
    Icons.credit_card,
    Icons.receipt,
    Icons.attach_money,
    Icons.trending_up,
    Icons.trending_down,
    Icons.bar_chart,
    Icons.pie_chart,
    Icons.show_chart,
    Icons.analytics,
    
    // Technology
    Icons.computer,
    Icons.laptop,
    Icons.phone_android,
    Icons.phone_iphone,
    Icons.tablet,
    Icons.watch,
    Icons.headphones,
    Icons.speaker,
    Icons.tv,
    Icons.camera_alt,
    Icons.videocam,
    Icons.mic,
    Icons.code,
    Icons.calculate,
    
    // Media & Creative
    Icons.palette,
    Icons.brush,
    Icons.color_lens,
    Icons.image,
    Icons.photo_library,
    Icons.photo_camera,
    
    // Documents & Notes
    Icons.description,
    Icons.note,
    Icons.note_add,
    Icons.edit_note,
    Icons.draw,
    Icons.create,
    Icons.edit,
    Icons.border_color,
    Icons.format_paint,
    Icons.text_snippet,
    Icons.sticky_note_2,
    Icons.attach_file,
    Icons.link,
    Icons.insert_link,
    
    // Tools & Building
    Icons.build,
    Icons.construction,
    Icons.handyman,
    Icons.auto_fix_high,
    Icons.auto_fix_normal,
    Icons.electric_bolt,
    Icons.flash_on,
    Icons.lightbulb,
    Icons.light_mode,
    Icons.dark_mode,
    Icons.wb_sunny,
    Icons.nightlight,
    Icons.bed,
    Icons.hotel_class,
    
    // Places & Services
    Icons.store,
    Icons.storefront,
    Icons.local_gas_station,
    Icons.local_pharmacy,
    Icons.local_hospital,
    Icons.local_police,
    Icons.local_fire_department,
    Icons.local_library,
    Icons.local_post_office,
    Icons.local_parking,
    Icons.local_atm,
    
    // Social & People
    Icons.account_circle,
    Icons.person,
    Icons.person_add,
    Icons.group,
    Icons.groups,
    Icons.people,
    Icons.people_outline,
    Icons.supervisor_account,
    Icons.family_restroom,
    Icons.volunteer_activism,
    Icons.celebration,
    
    // Achievements & Rewards
    Icons.badge,
    Icons.workspace_premium,
    Icons.emoji_events,
    Icons.military_tech,
    Icons.stars,
    Icons.workspace_premium_outlined,
    Icons.card_giftcard,
    Icons.card_membership,
    Icons.loyalty,
    Icons.redeem,
    Icons.local_offer,
    Icons.local_activity,
    
    // Tech & Connectivity
    Icons.qr_code,
    Icons.qr_code_scanner,
    Icons.qr_code_2,
    Icons.nfc,
    Icons.bluetooth,
    Icons.wifi,
    Icons.signal_wifi_4_bar,
    Icons.signal_cellular_4_bar,
    Icons.battery_full,
    Icons.power,
    Icons.power_off,
    Icons.power_settings_new,
    
    // Settings & Security
    Icons.settings,
    Icons.settings_applications,
    Icons.tune,
    Icons.build_circle,
    Icons.admin_panel_settings,
    Icons.security,
    Icons.lock,
    Icons.lock_open,
    Icons.vpn_key,
    Icons.password,
    Icons.fingerprint,
    Icons.face,
    Icons.face_retouching_natural,
    Icons.verified,
    Icons.verified_user,
    Icons.shield,
    Icons.privacy_tip,
    
    // Actions
    Icons.check_circle,
    Icons.check,
    Icons.add_circle,
    Icons.add,
    Icons.remove_circle,
    Icons.remove,
    Icons.delete,
    Icons.delete_forever,
    Icons.restore,
    Icons.restore_from_trash,
    Icons.archive,
    Icons.unarchive,
    Icons.download,
    Icons.upload,
    Icons.report,
    Icons.flag,
    Icons.block,
    Icons.cancel,
    Icons.close,
    
    // Cloud & Sync
    Icons.cloud_upload,
    Icons.cloud_download,
    Icons.cloud,
    Icons.cloud_done,
    Icons.cloud_off,
    Icons.cloud_sync,
    Icons.backup,
    Icons.sync,
    Icons.sync_alt,
    Icons.refresh,
    Icons.autorenew,
    Icons.cached,
    Icons.update,
    Icons.system_update,
    Icons.install_mobile,
    Icons.install_desktop,
    Icons.get_app,
    Icons.publish,
    Icons.file_upload,
    Icons.file_download,
    
    // Files & Folders
    Icons.folder,
    Icons.folder_open,
    Icons.folder_shared,
    Icons.insert_drive_file,
    Icons.drive_file_rename_outline,
    Icons.drive_file_move,
    Icons.drive_file_move_outline,
    Icons.drive_file_move_rtl,
    Icons.create_new_folder,
    Icons.folder_copy,
    Icons.folder_delete,
    Icons.folder_zip,
    Icons.folder_special,
    Icons.folder_off,
    Icons.content_copy,
    Icons.content_cut,
    Icons.content_paste,
    Icons.copy_all,
    Icons.cut,
    Icons.paste,
    
    // Language & Communication
    Icons.public,
    Icons.language,
    Icons.translate,
    Icons.g_translate,
    Icons.currency_exchange,
    Icons.confirmation_number,
    Icons.compass_calibration,
    Icons.explore_off,
  ];
  
  /// Available colors for forms (700 shade for better contrast)
  static final List<Color> availableColors = [
    Colors.deepPurple[700]!,
    Colors.blue[700]!,
    Colors.green[700]!,
    Colors.orange[700]!,
    Colors.red[700]!,
    Colors.pink[700]!,
    Colors.teal[700]!,
    Colors.indigo[700]!,
    Colors.amber[700]!,
    Colors.cyan[700]!,
    Colors.lime[700]!,
    Colors.brown[700]!,
  ];

  /// Predefined units for measurable tracking
  static const List<String> predefinedUnits = [
    'minutes',
    'hours',
    'km',
    'miles',
    'steps',
    'count',
    'times',
    'pages',
    'glasses',
    'cups',
    'liters',
    'calories',
    'kg',
    'lbs',
    'reps',
    'sets',
  ];
}

